import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Footer from "@/Components/WaveFooter";
import AuthProvider from "@/utils/SessionProvider";
import SmallFooter from "@/Components/SmallFooter";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Script from "next/script";
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        {/* <Script src="https://cdn.tailwindcss.com"></Script> */}

        <body className={montserrat.className}>
          <ToastContainer />
          {children}

          <div className="hidden sm:block">
            <Footer />
          </div>
          <div className="sm:hidden">
            <SmallFooter />
          </div>
          <footer></footer>
        </body>
      </AuthProvider>
    </html>
  );
}
